config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations', authorized_applications: 'oauth/authorized_applications'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: { format: :html }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show]
    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
    end

    resource :two_factor_authentication, only: [:show, :create, :destroy]
    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resource :follower_domains, only: [:show, :update]
  end

  resources :media, only: [:show]
  resources :tags,  only: [:show]

  # Remote follow
  resource :authorize_follow, only: [:show, :create]

  namespace :admin do
    resources :pubsubhubbub, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create, :show, :destroy]
    resources :settings, only: [:index, :update]
    resources :instances, only: [:index]

    resources :reports, only: [:index, :show, :update] do
      resources :reported_statuses, only: :destroy
    end

    resources :accounts, only: [:index, :show] do
      resource :reset, only: [:create]
      resource :silence, only: [:create, :destroy]
      resource :suspension, only: [:create, :destroy]
      resource :confirmation, only: [:create]
    end
  end

  get '/admin', to: redirect('/admin/settings', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # ActivityPub
    namespace :activitypub do
      get '/users/:id/outbox', to: 'outbox#show', as: :outbox
      get '/statuses/:id', to: 'activities#show_status', as: :status
      resources :notes, only: [:show]
    end

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        member do
          get :context
          get :card
          get :reblogged_by
          get :favourited_by

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      get '/timelines/home',     to: 'timelines#home', as: :home_timeline
      get '/timelines/public',   to: 'timelines#public', as: :public_timeline
      get '/timelines/tag/:id',  to: 'timelines#tag', as: :hashtag_timeline

      get '/search', to: 'search#index', as: :search

      resources :follows,    only: [:create]
      resources :media,      only: [:create]
      resources :apps,       only: [:create]
      resources :blocks,     only: [:index]
      resources :mutes,      only: [:index]
      resources :favourites, only: [:index]
      resources :reports,    only: [:index, :create]

      resource :instance, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
          post :dismiss
        end
      end

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
          patch :update_credentials
          get :search
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end
      end
    end

    namespace :web do
      resource :settings, only: [:update]
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#show'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route',
    via: :all,
    to: 'application#raise_not_found',
    format: false
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  before_action :set_body_classes
  before_action :set_instance_presenter, only: [:show, :more]

  def show; end

  def more; end

  def terms; end

  private

  def new_user
    User.new.tap(&:build_account)
  end
  helper_method :new_user

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end

  def set_body_classes
    @body_classes = 'about-body'
  end
end

app/views/about/_contact.html.haml
.panel
  .panel-header= t 'about.contact'
  .panel-body
    - if contact.contact_account
      .owner
        .avatar= image_tag contact.contact_account.avatar.url
        .name
          = link_to TagManager.instance.url_for(contact.contact_account) do
            %span.display_name.emojify= display_name(contact.contact_account)
            %span.username= "@#{contact.contact_account.acct}"

    - if contact.site_contact_email
      .contact-email
        = t 'about.business_email'
        %strong= contact.site_contact_email

app/views/about/_links.html.haml
.panel
  .panel-header= t 'about.links'
  .panel-list
    %ul
      - if user_signed_in?
        %li= link_to t('about.get_started'), root_path
      - else
        %li= link_to t('about.get_started'), new_user_registration_path
        %li= link_to t('auth.login'), new_user_session_path
      %li= link_to t('about.terms'), terms_path
      %li= link_to t('about.source_code'), 'https://github.com/tootsuite/mastodon'

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  = f.simple_fields_for :account do |account_fields|
    = account_fields.input :username,
      autofocus: true,
      placeholder: t('simple_form.labels.defaults.username'),
      required: true,
      input_html: { 'aria-label' => t('simple_form.labels.defaults.username') }

  = f.input :email,
    placeholder: t('simple_form.labels.defaults.email'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }
  = f.input :password,
    autocomplete: "off",
    placeholder: t('simple_form.labels.defaults.password'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }
  = f.input :password_confirmation,
    autocomplete: "off",
    placeholder: t('simple_form.labels.defaults.confirm_password'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password') }

  .actions
    = f.button :button, t('about.get_started'), type: :submit

  .info
    = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
    ·
    = link_to t('about.about_this'), about_more_path

app/views/about/_version.html.haml
.panel
  .panel-header= t 'about.version'
  .panel-body
    %strong= version.version_number

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

.wrapper.thicc
  .sidebar-layout
    .main
      .panel
        %h2= site_hostname

        - unless @instance_presenter.site_description.blank?
          %p= @instance_presenter.site_description.html_safe

      .information-board
        .section
          %span= t 'about.user_count_before'
          %strong= number_with_delimiter @instance_presenter.user_count
          %span= t 'about.user_count_after'
        .section
          %span= t 'about.status_count_before'
          %strong= number_with_delimiter @instance_presenter.status_count
          %span= t 'about.status_count_after'
        .section
          %span= t 'about.domain_count_before'
          %strong= number_with_delimiter @instance_presenter.domain_count
          %span= t 'about.domain_count_after'

      - unless @instance_presenter.site_extended_description.blank?
        .panel= @instance_presenter.site_extended_description.html_safe

    .sidebar
      = render 'contact', contact: @instance_presenter
      = render 'links'
      = render 'version', version: @instance_presenter

app/views/about/show.html.haml
- content_for :header_tags do
  = javascript_include_tag 'application_public', integrity: true, crossorigin: 'anonymous'

- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %meta{ property: 'og:site_name', content: site_title }/
  %meta{ property: 'og:url', content: about_url }/
  %meta{ property: 'og:type', content: 'website' }/
  %meta{ property: 'og:title', content: site_hostname }/
  %meta{ property: 'og:description', content: strip_tags(@instance_presenter.site_description.presence || t('about.about_mastodon')) }/
  %meta{ property: 'og:image', content: asset_url('mastodon_small.jpg') }/
  %meta{ property: 'og:image:width', content: '400' }/
  %meta{ property: 'og:image:height', content: '400' }/
  %meta{ property: 'twitter:card', content: 'summary' }/

.wrapper
  %h1
    = image_tag 'logo.png'
    Mastodon @ La Quadrature du Net
    = Setting.site_title

  %p Mastodon est un serveur <em>libre</em> de réseautage social. Alternative <em>décentralisée</em> aux plateformes commerciales, la monopolisation de vos communications par une entreprise unique est évitée. Tout un chacun peut faire tourner Mastodon et participer au <em>réseau social</em> de manière transparente.
  %p Cette instance de Mastodon est installée, maintenue et supervisée par l'équipe des bénévoles de <a href="https://www.laquadrature.net/">la Quadrature du Net, association de défense des libertés</a>.

  .screenshot-with-signup
    .mascot= image_tag 'fluffy-elephant-friend.png'

    - if @instance_presenter.open_registrations
      = render 'registration'
    - else
      .closed-registrations-message
        - if @instance_presenter.closed_registrations_message.blank?
          %p= t('about.closed_registrations')
        - else
          = @instance_presenter.closed_registrations_message.html_safe
        .info
          = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
          ·
          = link_to t('about.other_instances'), 'https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/List-of-Mastodon-instances.md'
          ·
          = link_to t('about.about_this'), about_more_path

  %h3= t('about.features_headline')

  .features-list
    .features-list__column
      %ul.fa-ul
        %li
          = fa_icon('li check-square')
          = t 'about.features.chronology'
        %li
          = fa_icon('li check-square')
          = t 'about.features.public'
        %li
          = fa_icon('li check-square')
          = t 'about.features.characters'
        %li
          = fa_icon('li check-square')
          = t 'about.features.gifv'
    .features-list__column
      %ul.fa-ul
        %li
          = fa_icon('li check-square')
          = t 'about.features.privacy'
        %li
          = fa_icon('li check-square')
          = t 'about.features.blocks'
        %li
          = fa_icon('li check-square')
          = t 'about.features.ethics'
        %li
          = fa_icon('li check-square')
          = t 'about.features.api'

  - unless @instance_presenter.site_description.blank?
    %h3= t('about.description_headline', domain: site_hostname)
    %p= @instance_presenter.site_description.html_safe

  .actions
    .info
      = link_to t('about.terms'), terms_path
      ·
      = link_to t('about.apps'), 'https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md'
      ·
      = link_to t('about.source_code'), 'https://github.com/tootsuite/mastodon'
      ·
      = link_to t('about.other_instances'), 'https://instances.mastodon.xyz/'

app/views/about/terms.en.html.haml
  #{Rails.configuration.x.local_domain} Conditions générales d'utilisation du service Mamot.fr

.wrapper

  %h2
    %a.anchor{"aria-hidden" => "true", :href => "#conditions-g%C3%A9n%C3%A9rales-dutilisation-du-service-mamotfr", :id => "user-content-conditions-générales-dutilisation-du-service-mamotfr"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Conditions générales d'utilisation du service Mamot.fr
  %h3
    %a#user-content-service--garanties.anchor{"aria-hidden" => "true", :href => "#service--garanties"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Service &amp; garanties
  %p
    La Quadrature du Net (« Nous », par la suite) met en place un service gratuit de système de publication Mastodon [1] accessible à l'adresse
    %a{:href => "https://mamot.fr/"} https://mamot.fr/
    afin de favoriser des espaces d'expression publics basé sur des logiciels libres et décentralisés. L'accès au service est gratuit pour ne pas restreindre l'expression publique aux capacités financières.
  %p
    Toute personne (par la suite : « l'utilisateur·rice » ou « Vous ») peut y ouvrir un compte en précisant une adresse email et un mot de passe [2].
    Nous essayons de garantir la pérennité, la qualité et la sécurité du service, mais aucune garantie n'est apportée sur ces points.
    L'infrastructure est gérée par une équipe technique [3] et une équipe contenus [4]. Afin d'être tenu·e au courant des évolutions et dysfonctionnements du service, il est fortement recommandé de suivre le compte 
    %a{:href => "https://mamot.fr/@admin"}> @admin@mamot.fr
    \.
  %h3
    %a.anchor{"aria-hidden" => "true", :href => "#confidentialit%C3%A9--vie-priv%C3%A9e", :id => "user-content-confidentialité--vie-privée"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Confidentialité &amp; vie privée
  %p
    L'utilisateur·rice est informé·e que Mastodon a pour but principal de publier des informations à une liste d'« abonné·e·s » ou directement au public. En raison des limitations du protocole oStatus utilisé, la confidentialité des messages dits « directs » ne peut être garantie. [9]. Ils sont susceptibles d'être accessibles aux administrateur·ice·s de mamot.fr ou d'autres instances, voir au public en cas de problème sur la sécurité de Mastodon, de mamot.fr ou d'autres instances.
    Tout message que vous supprimez de votre compte l'est sur mamot.fr, mais peut être conservé par d'autres instances ne respectant pas le protocole de Mastodon.
  %h3
    %a.anchor{"aria-hidden" => "true", :href => "#donn%C3%A9es-concern%C3%A9es", :id => "user-content-données-concernées"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Données concernées
  %h4
    %a#user-content-suppression-de-compte.anchor{"aria-hidden" => "true", :href => "#suppression-de-compte"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Suppression de compte
  %p À ce jour, l'application Mastodon ne vous permet pas de supprimer vous-même votre compte. Si vous souhaitez supprimer votre compte, merci de contacter l'équipe technique [3] en précisant l'adresse mail utilisée pour vous inscrire ainsi que votre nom d'utilisateur·rice.
  %h4
    %a.anchor{"aria-hidden" => "true", :href => "#acc%C3%A8s-aux-donn%C3%A9es", :id => "user-content-accès-aux-données"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Accès aux données
  %p
    Chacun·e peut accéder à ses données publiques à tout moment en se rendant à l'adresse appropriée [5].
    Les autres données (voir ci-dessous) peuvent être obtenues conformément à la loi de 1978 [6].
    En dehors des messages publiés par l'utilisateur·rice, nous conservons les informations suivantes :
  %ul
    %li pendant une semaine, l'ensemble des accès au site mamot.fr (comprenant l'adresse IP, la page demandée, le navigateur, le referrant, la taille et le code de la réponse), à des fins de contrôle qualité ;
    %li pendant un an, les mêmes informations, uniquement pour les appels à une page de publication de contenu, tel que requis par la loi [8] ;
    %li sans limite de durée, l'ensemble des rapports de contenus problématiques signalés par les utilisateurs·rices, ainsi que l'action réalisée par l'équipe contenus de La Quadrature du Net.
  %h4
    %a#user-content-diffusion-et-exploitation.anchor{"aria-hidden" => "true", :href => "#diffusion-et-exploitation"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Diffusion et exploitation
  %p
    Nous ne faisons aucune exploitation commerciale de vos données.
    Les contenus que vous publiez sur mamot.fr ne sont diffusés que dans le cadre de Mastodon. Nous nous engageons à ne diffuser ou commercialiser ni ces contenus, ni les données privées [7]. En revanche, nous ne pouvons empêcher des tiers de collecter des contenus diffusés publiquement par l'intermédiaire de Mastodon.
  %h2
    %a.anchor{"aria-hidden" => "true", :href => "#mod%C3%A9ration", :id => "user-content-modération"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Modération
  %ul
    %li Vous ne devez pas utiliser mamot.fr pour envoyer, publier, distribuer ou diffuser tout contenu illégal, diffamatoire, harcelant, abusif ou autrement répréhensible.
    %li Si vous publiez des contenus susceptibles de heurter (sexualité, violence...), nous vous encourageons à utiliser la fonctionnalité du « CW ». De l'anglais « Content Warning », ce système cache votre message en le précédant d'un avertissement de votre choix.
    %li Les bots et automatismes sont acceptés tant que leur utilisation n'est pas abusive ou déplaisante pour les autres usagers, notamment s'ils publient un nombre de messages raisonnable.
    %li Les organisations à but lucratif sont fortement encouragés à contribuer au développement de Mastodon, à mettre en place leur propre instance, ou à disposer de comptes sur d'autres instances. Nous n'acceptons pas les comptes pratiquant le démarcharge commercial.
  %p
    Tout contenu et tout compte ne respectant pas ces conditions pourra être rendu invisible aux flux locaux et fédéraux [11], ou supprimé.
    Si ces conditions ne vous conviennent pas, nous vous invitons à rejoindre une autre instance ou à créer la vôtre.
  %h4
    %a#user-content-blocage-et-signalement.anchor{"aria-hidden" => "true", :href => "#blocage-et-signalement"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Blocage et signalement
  %p
    Vous pouvez bloquer vous-même les comptes qui posent problème : lorsque vous consultez le profil de l'utilisateur·ice, cliquez sur le bouton « 3 lignes horizontales » sur la page du compte concerné, puis sur « Bloquer ».
    Vous pouvez nous signaler un contenu ou un compte utilisateur·rice ne respectant ces conditions. Pour cela, vous pouvez soit :
  %ul
    %li Cliquer sur le menu « ... » puis « Signaler » le message ou le compte, en l'accompagnant d'une explication.
    %li
      Envoyer un email à
      %a{:href => "mailto:mamot@laquadrature.net"} mamot@laquadrature.net
      [4], en indiquant le lien URL [10] vers le contenu incriminé (si c'est un message particulier, cliquez sur la DATE/HEURE du message pour trouver son adresse précise)
  %p
    Nous envoyons automatiquement un message à tout propriétaire de compte quand son compte ou un de ses messages a fait l'objet d'un signalement. L'auteur du signalement ainsi que le message de signalement sont gardés anonymes.
    À des fins de transparence, les messages ou les comptes mis sous « silence » [11] ou bloqués seront référencés sur une page dédiée [12].
  %h2
    %a#user-content-modifications-de-ces-cgu-licence.anchor{"aria-hidden" => "true", :href => "#modifications-de-ces-cgu-licence"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Modifications de ces CGU, Licence
  %p
    Ces conditions d'utilisation sont accessibles à la page
    %a{:href => "https://mamot.fr/terms"} https://mamot.fr/terms
  %p
    En cas de mise à jour de ces CGU, les utilisateurs·rices seront prévenus une semaine avant leur mise en œuvre via un message envoyé sur le compte
    %a{:href => "https://mamot.fr/@admin"} https://mamot.fr/@admin
  %p Les anciennes versions resteront disponibles à cette adresse.
  %p Ces conditions d'utilisations sont publiées sous licence CC0
  %p CGU MAMOT V0-2017-04-22.
  %h2
    %a#user-content-notes.anchor{"aria-hidden" => "true", :href => "#notes"}>
      %span.octicon.octicon-link{"aria-hidden" => "true"}
    Notes
  %ul
    %li
      [1] Mastodon est un logiciel libre dont le code source est disponible à l'adresse
      %a{:href => "https://github.com/tootsuite/mastodon/"} https://github.com/tootsuite/mastodon/
    %li [2] Les mots de passe ne sont pas stockés en clair sur les serveurs
    %li
      [3] joignable à
      = succeed "," do
        %a{:href => "mailto:sysadmin@laquadrature.net"} sysadmin@laquadrature.net
    %li
      [4] joignable à
      = succeed "," do
        %a{:href => "mailto:mamot@laquadrature.net"} mamot@laquadrature.net
    %li
      [5]
      %a{:href => "https://mamot.fr/settings/export"} https://mamot.fr/settings/export
    %li [6] Pour accéder à vos informations, conformément à la loi de 1978, écrivez à La Quadrature du Net, 60 rue des Orteaux, 75020 Paris. En précisant bien le nom d'utilisateur·rice mamot.fr concerné.
    %li
      [7] Pour plus d'information :
      %a{:href => "https://www.cnil.fr/fr/le-droit-dacces"} https://www.cnil.fr/fr/le-droit-dacces
      \&amp;
      %a{:href => "https://www.cnil.fr/fr/modele/courrier/exercer-son-droit-dacces"} https://www.cnil.fr/fr/modele/courrier/exercer-son-droit-dacces
    %li
      [8]
      %a{:href => "https://www.legifrance.gouv.fr/eli/decret/2006/3/24/JUSD0630025D/jo/texte"} https://www.legifrance.gouv.fr/eli/decret/2006/3/24/JUSD0630025D/jo/texte
    %li [9] Si vous souhaitez échanger de manière confidentielle des messages avec d'autres utilisateurs·rices, préférez Signal ou Jabber avec OTR ou OMemo
    %li
      [10] par exemple :
      %a{:href => "https://mamot.fr/@admin/17935"} https://mamot.fr/@admin/17935
    %li [11] Un compte mis en « Silence » voit ses messages rendus invisibles sur les pages « Fil public local » et « Fil public global ». Seul·e·s ses abonné·e·s voient ses messages.
    %li [12] ... URL à déterminer ...
  